### ISSUE TITLE
Does not work on MW 1.41

### ISSUE THREAD

**Issue by dolfinus** [Universal-Omega/Preloader#5]
After enabling extension edit action is failing with error:
```
[Zgnaqb2e4omLh6ycsS0fEgAAAAA] /w/index.php?title=Test&action=edit Error: Class "Revision" not found

Backtrace:

from /public/w/extensions/Preloader/Preloader.class.php(42)
#0 /public/w/extensions/Preloader/Preloader.class.php(9): Preloader::sourceText(string)
#1 /public/w/includes/HookContainer/HookContainer.php(161): Preloader::mainHook(string, MediaWiki\Title\Title)
#2 /public/w/includes/HookContainer/HookRunner.php(1484): MediaWiki\HookContainer\HookContainer->run(string, array)
#3 /public/w/includes/editpage/PreloadedContentBuilder.php(95): MediaWiki\HookContainer\HookRunner->onEditFormPreloadText(string, MediaWiki\Title\Title)
#4 /public/w/includes/editpage/EditPage.php(1456): MediaWiki\EditPage\PreloadedContentBuilder->getPreloadedContent(MediaWiki\Page\PageIdentityValue, MediaWiki\User\User, NULL, array, NULL)
#5 /public/w/includes/editpage/EditPage.php(1385): MediaWiki\EditPage\EditPage->getContentObject(WikitextContent)
#6 /public/w/includes/editpage/EditPage.php(728): MediaWiki\EditPage\EditPage->initialiseForm()
#7 /public/w/includes/actions/EditAction.php(66): MediaWiki\EditPage\EditPage->edit()
#8 /public/w/includes/MediaWiki.php(583): EditAction->show()
#9 /public/w/includes/MediaWiki.php(363): MediaWiki->performAction(Article, MediaWiki\Title\Title)
#10 /public/w/includes/MediaWiki.php(960): MediaWiki->performRequest()
#11 /public/w/includes/MediaWiki.php(613): MediaWiki->main()
#12 /public/w/index.php(50): MediaWiki->run()
#13 /public/w/index.php(46): wfIndexMain()
#14 {main}
```

It looks like Revision.php was [removed in MW 1.37](https://www.mediawiki.org/wiki/Manual:Revision.php)

**Comment by Universal-Omega** [comment]
This is fixed in my fork, at least in the master branch. It's the reason I forked to begin with. Please try updating.

**Comment by dolfinus** [comment]
What fork exactly?

**Comment by Universal-Omega** [comment]
> What fork exactly?

This repo is a fork of the original version. I did not original write this extension just maintained it after the original no longer worked.

**Comment by dolfinus** [comment]
> This repo is a fork of the original version

I have no idea what the _original version_ is and there is the original repo is located. I've just downloaded latest tag from this repo:
![изображение](https://github.com/Universal-Omega/Preloader/assets/4661021/4fd3a277-9760-4a25-a6c4-34bfb7bad1fb)

Do these tags contain code of extension before it was adopted by new maintainer?

**Comment by Universal-Omega** [comment]
Download the master branch not tags
